<a href="https://colab.research.google.com/github/Sampath844/MLAssignment29-07-2024/blob/main/assignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statistics as st

In [ ]:
A = pd.read_excel('Lab Session Data.xlsx', usecols = [1,2,3])
A.head()

Candies (#)  Mangoes (Kg)  Milk Packets (#)
0           20             6                 2
1           16             3                 6
2           27             6                 2
3           19             1                 2
4           24             4                 2

In [ ]:
B = pd.read_excel('Lab Session Data.xlsx',usecols =[4])
B.head()

Payment (Rs)
0           386
1           289
2           393
3           110
4           280

In [ ]:
C = np.linalg.pinv(A)
X = np.dot(C,B)
print(X)


[[ 1.]
 [55.]
 [18.]]


# New Section

In [ ]:
# rank of A
print(np.linalg.matrix_rank(A))

3


In [ ]:
# q2 pseudo inverse of a matrix X
print(np.linalg.pinv(X))
# For prices
print(np.linalg.pinv(C))


[[0.00029851 0.01641791 0.00537313]]
[[20.  6.  2.]
 [16.  3.  6.]
 [27.  6.  2.]
 [19.  1.  2.]
 [24.  4.  2.]
 [22.  1.  5.]
 [15.  4.  2.]
 [18.  4.  2.]
 [21.  1.  4.]
 [16.  2.  4.]]


In [ ]:
#mark customers Q3
myexcel = pd.read_excel('Lab Session Data.xlsx')
myexcel['Status'] = myexcel['Payment (Rs)'].apply(lambda x: "RICH" if x > 200 else "POOR")
myexcel.head()






Customer  Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs)  \
0      C_1           20             6                 2           386   
1      C_2           16             3                 6           289   
2      C_3           27             6                 2           393   
3      C_4           19             1                 2           110   
4      C_5           24             4                 2           280   

   Unnamed: 5  Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  ...  \
0         NaN         NaN         NaN         NaN         NaN  ...   
1         NaN         NaN         NaN         NaN         NaN  ...   
2         NaN         NaN         NaN         NaN         NaN  ...   
3         NaN         NaN         NaN         NaN         NaN  ...   
4         NaN         NaN         NaN         NaN         NaN  ...   

   Unnamed: 13  Unnamed: 14  Unnamed: 15  Unnamed: 16  Unnamed: 17  \
0          NaN          NaN          NaN          NaN          NaN   
1          NaN          NaN          NaN          NaN          NaN   
2          NaN          NaN          NaN          NaN          NaN   
3          NaN          NaN          NaN          NaN          NaN   
4          NaN          NaN          NaN          NaN          NaN   

   Unnamed: 18  Candy  Mango  Milk  Status  
0          NaN    1.0   55.0  18.0    RICH  
1          NaN    NaN    NaN   NaN    RICH  
2          NaN    NaN    NaN   NaN    RICH  
3          NaN    NaN    NaN   NaN    POOR  
4          NaN    NaN    NaN   NaN    RICH  

[5 rows x 23 columns]

In [ ]:
#irctc mean and variance
irctc = pd.read_excel('Lab Session Data.xlsx',sheet_name ='IRCTC Stock Price')
irctc.head()
mean = st.mean(irctc['Price'])
print(mean)
var = st.variance(irctc['Price'])
print(var)



1560.663453815261
58732.365352539186
249


In [ ]:
#calcuate wed mean
mean_new=0
for i in range(len(irctc)):
  if(irctc['Day'] == "Wed"):
    mean_new = st.mean(irctc['Price'])
print(mean_new)

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().